In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0], a[1], a[2])

1 2 3


In [5]:
a[0] = 5
print(a)

[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [7]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [8]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [12]:
e = np.random.random((2,2))
print(e)

[[0.51934806 0.22681838]
 [0.70832988 0.10009999]]
