In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [3]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [4]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [5]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [6]:
print(x * y)

[[ 5. 12.]
 [21. 32.]]


In [7]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [8]:
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
v = np.array([9,10])
w = np.array([11, 12])

In [12]:
print(v.dot(w))

219


In [13]:
print(np.dot(v, w))

219


In [14]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(v))

[29 67]


In [15]:
print(np.dot(x, v))

[29 67]


In [16]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [17]:
print(np.dot(x, y))

In [ ]:
print(np.sum(x))

In [ ]:
print(np.sum(x, axis=0))

In [ ]:
print(np.sum(x, axis=1))

In [ ]:
print(x)

In [ ]:
print(x.T)