In [1]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [2]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [3]:
print(a[[0, 0], [1, 1]])

[2 2]


In [4]:
print(np.array([a[0, 1], a[0, 1]]))

[2 2]


In [5]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
c = np.array([0, 2, 0, 1])
print(b[np.arange(4), c])

[ 1  6  7 11]


In [7]:
b[np.arange(4), c] += 10
print(b)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
