In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]

In [3]:
print(a[0, 1])

2


In [4]:
b[0, 0] = 77
print(a[0, 1])

77


In [5]:
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = c[1, :]
row_r2 = c[1:2, :]

In [6]:
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [7]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [8]:
col_r1 = c[:, 1]
col_r2 = c[:, 1:2]

In [9]:
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [10]:
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)
